In [537]:
import emoji
import pandas as pd
import numpy as np
from keras.layers import *
from keras.models import *
from keras.utils import to_categorical

In [538]:
emoji.EMOJI_UNICODE

{':1st_place_medal:': '🥇',
 ':2nd_place_medal:': '🥈',
 ':3rd_place_medal:': '🥉',
 ':AB_button_(blood_type):': '🆎',
 ':ATM_sign:': '🏧',
 ':A_button_(blood_type):': '🅰',
 ':Afghanistan:': '🇦🇫',
 ':Albania:': '🇦🇱',
 ':Algeria:': '🇩🇿',
 ':American_Samoa:': '🇦🇸',
 ':Andorra:': '🇦🇩',
 ':Angola:': '🇦🇴',
 ':Anguilla:': '🇦🇮',
 ':Antarctica:': '🇦🇶',
 ':Antigua_&_Barbuda:': '🇦🇬',
 ':Aquarius:': '♒',
 ':Argentina:': '🇦🇷',
 ':Aries:': '♈',
 ':Armenia:': '🇦🇲',
 ':Aruba:': '🇦🇼',
 ':Ascension_Island:': '🇦🇨',
 ':Australia:': '🇦🇺',
 ':Austria:': '🇦🇹',
 ':Azerbaijan:': '🇦🇿',
 ':BACK_arrow:': '🔙',
 ':B_button_(blood_type):': '🅱',
 ':Bahamas:': '🇧🇸',
 ':Bahrain:': '🇧🇭',
 ':Bangladesh:': '🇧🇩',
 ':Barbados:': '🇧🇧',
 ':Belarus:': '🇧🇾',
 ':Belgium:': '🇧🇪',
 ':Belize:': '🇧🇿',
 ':Benin:': '🇧🇯',
 ':Bermuda:': '🇧🇲',
 ':Bhutan:': '🇧🇹',
 ':Bolivia:': '🇧🇴',
 ':Bosnia_&_Herzegovina:': '🇧🇦',
 ':Botswana:': '🇧🇼',
 ':Bouvet_Island:': '🇧🇻',
 ':Brazil:': '🇧🇷',
 ':British_Indian_Ocean_Territory:': '🇮🇴',
 ':British_Virgin_Is

In [539]:
emoji_dict = {
    0:"\u2764\uFE0F",
    1:":baseball:",
    2:":grinning_face_with_big_eyes:",
    3:":disappointed_face:",
    4:":fork_and_knife:",
    5:":hundred_points:",
    6:":fire:",
    7:":face_blowing_a_kiss:",
    8:":chestnut:",
    9:":flexed_biceps:"
}

In [540]:
for e in emoji_dict.values():
    print(emoji.emojize(e))

❤️
⚾
😃
😞
🍴
💯
🔥
😘
🌰
💪


In [541]:
train_x = pd.read_csv('emojify_train_x.csv',header=None)
train_y = pd.read_csv('Emojify_Y_train.csv',header=None)
test_x = pd.read_csv('emojiy_test_x.csv',header=None)
test_y = pd.read_csv('emojiy_y_test.csv',header=None)

In [542]:
X_train = np.array(train_x)
X_train = X_train.reshape((-1,))

In [543]:
X_train

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life', 'I love you mum', 'Stop saying bullshit',
       'congratulations on your acceptance', 'The assignment is too long',
       'I want to go play', 'she did not answer my text',
       'Your stupidity has no limit', 'how many points did he score',
       'my algorithm performs poorly', 'I got approved',
       'Stop shouting at me', 'Sounds like a fun plan ha ha',
       'no one likes him', 'the game just finished',
       'I will celebrate soon', 'So sad you are not coming',
       'She is my dearest love', 'Good job', 'It was funny lol',
       'candy is life', 'The chicago cubs won again', 'I am hungry',
       'I am so excited to see you after so long',
       'you did well on you exam', 'lets brunch some day',
       'he is so cute', 'How dare you ask that',
       'do you want to join me for dinner', 'I said yes',
       'she is attr

In [548]:
X_train.shape

(132,)

In [549]:
Y_train = np.array(train_y)

In [550]:
Y_train = Y_train.reshape((-1,))

In [551]:
Y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [552]:
Y_train.shape

(132,)

In [553]:
for i in range(131):
    s=emoji_dict[Y_train[i]]
    print(X_train[i],emoji.emojize(s))

never talk to me again 😞
I am proud of your achievements 😃
It is the worst day in my life 😞
Miss you so much ❤️
food is life 🍴
I love you mum ❤️
Stop saying bullshit 😞
congratulations on your acceptance 😃
The assignment is too long 😞
I want to go play ⚾
she did not answer my text 😞
Your stupidity has no limit 😞
how many points did he score ⚾
my algorithm performs poorly 😞
I got approved 😃
Stop shouting at me 😞
Sounds like a fun plan ha ha 😃
no one likes him 😞
the game just finished ⚾
I will celebrate soon 😃
So sad you are not coming 😞
She is my dearest love ❤️
Good job 😃
It was funny lol 😃
candy is life 😃
The chicago cubs won again ⚾
I am hungry 🍴
I am so excited to see you after so long 😃
you did well on you exam 😃
lets brunch some day 🍴
he is so cute ❤️
How dare you ask that 😞
do you want to join me for dinner 🍴
I said yes 😃
she is attractive ❤️
you suck 😞
she smiles a lot 😃
he is laughing 😃
she takes forever to get ready 😞
French macaroon is so tasty 🍴
we made it 😃
I am excited 😃
I 

In [554]:
Y_train = to_categorical(Y_train)
Y_train.shape

(132, 5)

In [555]:
Y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0.

In [556]:
embeddings = {}
f = open('glove.6B.50d.txt',encoding='utf-8')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:],dtype='float')
    embeddings[word] = coefs
f.close()

In [557]:
emb_dim = embeddings["eat"].shape[0]
emb_dim

50

In [558]:
def embedding_layer(X):
    maxlen = 10
    embedding_out = np.zeros((X.shape[0],maxlen,emb_dim))
    for ix in range(X.shape[0]):
        X[ix] = str(X[ix])
        X[ix] = X[ix].split()
        for ij in range(len(X[ix])):
            embedding_out[ix][ij] = embeddings[X[ix][ij].lower()]
    return embedding_out

In [559]:
embedding_train = embedding_layer(X_train)

In [560]:
embedding_train.shape

(132, 10, 50)

In [561]:
Y_train.shape

(132, 5)

In [562]:
model = Sequential()
model.add(LSTM(64,input_shape=(10,50),return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(64,return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(5))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=["accuracy"])
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_18 (LSTM)               (None, 10, 64)            29440     
_________________________________________________________________
dropout_18 (Dropout)         (None, 10, 64)            0         
_________________________________________________________________
lstm_19 (LSTM)               (None, 64)                33024     
_________________________________________________________________
dropout_19 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_13 (Dense)             (None, 5)                 325       
_________________________________________________________________
activation_12 (Activation)   (None, 5)                 0         
Total params: 62,789
Trainable params: 62,789
Non-trainable params: 0
_________________________________________________

In [563]:
model.fit(embedding_train,Y_train,epochs=100,batch_size=64,shuffle=True,validation_split=0.2)

Train on 105 samples, validate on 27 samples
Epoch 1/100
105/105 [==============================] - 4s 36ms/step - loss: 1.5849 - accuracy: 0.2762 - val_loss: 1.6043 - val_accuracy: 0.2593
Epoch 2/100
105/105 [==============================] - 0s 1ms/step - loss: 1.5487 - accuracy: 0.3714 - val_loss: 1.6092 - val_accuracy: 0.2593
Epoch 3/100
105/105 [==============================] - 0s 1ms/step - loss: 1.5021 - accuracy: 0.4000 - val_loss: 1.6202 - val_accuracy: 0.2222
Epoch 4/100
105/105 [==============================] - 0s 1ms/step - loss: 1.4708 - accuracy: 0.3905 - val_loss: 1.6402 - val_accuracy: 0.2222
Epoch 5/100
105/105 [==============================] - 0s 1ms/step - loss: 1.4544 - accuracy: 0.4381 - val_loss: 1.6549 - val_accuracy: 0.2222
Epoch 6/100
105/105 [==============================] - 0s 1ms/step - loss: 1.4149 - accuracy: 0.4571 - val_loss: 1.6634 - val_accuracy: 0.2222
Epoch 7/100
105/105 [==============================] - 0s 988us/step - loss: 1.3951 - accuracy: 

105/105 [==============================] - 0s 1ms/step - loss: 0.0334 - accuracy: 1.0000 - val_loss: 1.0166 - val_accuracy: 0.7778
Epoch 58/100
105/105 [==============================] - 0s 1ms/step - loss: 0.0307 - accuracy: 1.0000 - val_loss: 1.2188 - val_accuracy: 0.7037
Epoch 59/100
105/105 [==============================] - 0s 1ms/step - loss: 0.0693 - accuracy: 0.9810 - val_loss: 1.0607 - val_accuracy: 0.7037
Epoch 60/100
105/105 [==============================] - 0s 1ms/step - loss: 0.0256 - accuracy: 1.0000 - val_loss: 0.9340 - val_accuracy: 0.7407
Epoch 61/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1165 - accuracy: 0.9714 - val_loss: 0.8321 - val_accuracy: 0.7778
Epoch 62/100
105/105 [==============================] - 0s 1ms/step - loss: 0.0284 - accuracy: 0.9905 - val_loss: 1.4370 - val_accuracy: 0.6667
Epoch 63/100
105/105 [==============================] - 0s 1ms/step - loss: 0.1441 - accuracy: 0.9524 - val_loss: 1.2981 - val_accuracy: 0.5926
Epoch

In [583]:
test = pd.read_csv("test_emoji.csv",header=None)
test = np.array(test)

In [584]:
test

array([['I want to eat\t', 4],
       ['he did not answer\t', 3],
       ['he got a raise\t', 2],
       ['she got me a present\t', 0],
       ['ha ha ha it was so funny\t', 2],
       ['he is a good friend\t', 0],
       ['I am upset\t', 0],
       ['We had such a lovely dinner tonight\t', 0],
       ['where is the food\t', 4],
       ['Stop making this joke ha ha ha\t', 2],
       ['where is the ball\t', 1],
       ['work is hard\t', 3],
       ['This girl is messing with me\t', 3],
       ['are you serious ha ha\t', 2],
       ['Let us go play baseball\t', 1],
       ['This stupid grader is not working \t', 3],
       ['work is horrible\t', 3],
       ['Congratulation for having a baby\t', 2],
       ['stop messing around\t', 3],
       ['any suggestions for dinner\t', 4],
       ['I love taking breaks\t', 0],
       ['you brighten my day\t', 2],
       ['I boiled rice\t', 4],
       ['she is a bully\t', 3],
       ['Why are you feeling bad\t', 3],
       ['I am upset\t', 3],
      

In [585]:
for i in range(55):
    test[i][0] = test[i][0][:-1].strip()

In [586]:
test

array([['I want to eat', 4],
       ['he did not answer', 3],
       ['he got a raise', 2],
       ['she got me a present', 0],
       ['ha ha ha it was so funny', 2],
       ['he is a good friend', 0],
       ['I am upset', 0],
       ['We had such a lovely dinner tonight', 0],
       ['where is the food', 4],
       ['Stop making this joke ha ha ha', 2],
       ['where is the ball', 1],
       ['work is hard', 3],
       ['This girl is messing with me', 3],
       ['are you serious ha ha', 2],
       ['Let us go play baseball', 1],
       ['This stupid grader is not working', 3],
       ['work is horrible', 3],
       ['Congratulation for having a baby', 2],
       ['stop messing around', 3],
       ['any suggestions for dinner', 4],
       ['I love taking breaks', 0],
       ['you brighten my day', 2],
       ['I boiled rice', 4],
       ['she is a bully', 3],
       ['Why are you feeling bad', 3],
       ['I am upset', 3],
       ['I worked during my birthday', 3],
       ['My gran

In [607]:
X_test = np.array(test)

In [608]:
X_test = pd.DataFrame(X_test)

In [611]:
X_test = np.array(X_test[0])

In [613]:
X_test.shape

(56,)

In [614]:
X_test

array(['I want to eat', 'he did not answer', 'he got a raise',
       'she got me a present', 'ha ha ha it was so funny',
       'he is a good friend', 'I am upset',
       'We had such a lovely dinner tonight', 'where is the food',
       'Stop making this joke ha ha ha', 'where is the ball',
       'work is hard', 'This girl is messing with me',
       'are you serious ha ha', 'Let us go play baseball',
       'This stupid grader is not working', 'work is horrible',
       'Congratulation for having a baby', 'stop messing around',
       'any suggestions for dinner', 'I love taking breaks',
       'you brighten my day', 'I boiled rice', 'she is a bully',
       'Why are you feeling bad', 'I am upset',
       'I worked during my birthday',
       'My grandmother is the love of my life', 'enjoy your break',
       'valentine day is near', 'I miss you so much', 'throw the ball',
       'My life is so boring', 'she said yes', 'will you be my valentine',
       'he can pitch really well',

In [615]:
X_test.shape

(56,)

In [616]:
type(X_test[0])

str

In [617]:
Y_test = np.zeros((test.shape[0],))
for i in range(test.shape[0]):
     Y_test[i] = test[i][1]

In [618]:
Y_test.shape

(56,)

In [619]:
Y_test

array([4., 3., 2., 0., 2., 0., 0., 0., 4., 2., 1., 3., 3., 2., 1., 3., 3.,
       2., 3., 4., 0., 2., 4., 3., 3., 3., 3., 0., 2., 0., 0., 1., 3., 2.,
       0., 1., 2., 4., 4., 2., 2., 2., 0., 1., 2., 0., 2., 2., 2., 3., 3.,
       0., 3., 2., 2., 3.])

In [620]:
embedding_test = embedding_layer(X_test)

In [621]:
embedding_test.shape

(56, 10, 50)

In [622]:
Y_test = to_categorical(Y_test)

In [628]:
pred = model.predict(embedding_test)

In [642]:
pred_emoji = np.zeros((X_test.shape[0],))

In [643]:
for i in range(X_test.shape[0]):
    j = np.argmax(pred[i])
    pred_emoji[i] = j

In [644]:
pred_emoji

array([4., 3., 3., 2., 2., 2., 3., 2., 4., 2., 1., 2., 0., 0., 1., 3., 3.,
       2., 3., 2., 2., 0., 4., 0., 3., 3., 2., 0., 1., 2., 0., 1., 0., 2.,
       0., 2., 2., 3., 4., 2., 2., 0., 0., 1., 2., 2., 3., 2., 0., 3., 3.,
       3., 3., 2., 3., 0.])

In [647]:
emoji.emojize(emoji_dict[pred_emoji[1]])

'😞'

In [651]:
X_show = np.array(test)
X_show = pd.DataFrame(X_show)
X_show = np.array(X_show[0])

In [652]:
X_show

array(['I want to eat', 'he did not answer', 'he got a raise',
       'she got me a present', 'ha ha ha it was so funny',
       'he is a good friend', 'I am upset',
       'We had such a lovely dinner tonight', 'where is the food',
       'Stop making this joke ha ha ha', 'where is the ball',
       'work is hard', 'This girl is messing with me',
       'are you serious ha ha', 'Let us go play baseball',
       'This stupid grader is not working', 'work is horrible',
       'Congratulation for having a baby', 'stop messing around',
       'any suggestions for dinner', 'I love taking breaks',
       'you brighten my day', 'I boiled rice', 'she is a bully',
       'Why are you feeling bad', 'I am upset',
       'I worked during my birthday',
       'My grandmother is the love of my life', 'enjoy your break',
       'valentine day is near', 'I miss you so much', 'throw the ball',
       'My life is so boring', 'she said yes', 'will you be my valentine',
       'he can pitch really well',

In [653]:
for i in range(X_test.shape[0]):
    print(X_show[i],emoji.emojize(emoji_dict[pred_emoji[i]]))

I want to eat 🍴
he did not answer 😞
he got a raise 😞
she got me a present 😃
ha ha ha it was so funny 😃
he is a good friend 😃
I am upset 😞
We had such a lovely dinner tonight 😃
where is the food 🍴
Stop making this joke ha ha ha 😃
where is the ball ⚾
work is hard 😃
This girl is messing with me ❤️
are you serious ha ha ❤️
Let us go play baseball ⚾
This stupid grader is not working 😞
work is horrible 😞
Congratulation for having a baby 😃
stop messing around 😞
any suggestions for dinner 😃
I love taking breaks 😃
you brighten my day ❤️
I boiled rice 🍴
she is a bully ❤️
Why are you feeling bad 😞
I am upset 😞
I worked during my birthday 😃
My grandmother is the love of my life ❤️
enjoy your break ⚾
valentine day is near 😃
I miss you so much ❤️
throw the ball ⚾
My life is so boring ❤️
she said yes 😃
will you be my valentine ❤️
he can pitch really well 😃
dance with me 😃
I am starving 😞
See you at the restaurant 🍴
I like to laugh 😃
I will go dance 😃
I like your jacket ❤️
i miss her ❤️
what is your f